config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  match "/upload" => "pages#upload", :via => :post
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @errors = []
  end

  def downloader

  end

  def upload
    output = GenerateOutputFile.call(params[:file])
    if output.success?
      send_data output.result.to_json, type: :json, disposition: 'attachment', filename: "output.json"
    else
      flash.now[:warning] = "Erro ao gerar arquivo de saída"
      @errors = output.errors
      render 'home'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ecommerce</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="ui padded grid">      
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/_flash_messages.html.erb
<% unless flash.empty? %>
  <% flash.each do |type, message| %>
    <div class="ui <%= type %> message">
      <i class="close icon"></i>
      <div class="header">
        <%= message %>
      </div>
      <% unless errors.empty? %>
        <ul class="list">
          <% errors.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      <% end %>
    </div>
  <% end  %>
<% end %>

app/views/pages/home.html.erb
<div class="row">
  <div class="ten wide column">
    <%= render "flash_messages", errors: @errors %>
  </div>
</div>
<div class="row">
  <div class="ten wide column">
    <%= link_to root_path, class: 'ui header' do %>
      <h1 class="ui header">Teste E-Commerce</h1>
    <% end %>
    <div class="ui divider">

    </div>
    <%= form_tag(upload_path, multipart: true, class: "ui form", id: "upload_form") do |form| %>
      <div class="field">
        <label for="file">Arquivo de entrada</label>
        <%= file_field_tag "file" %>
      </div>

      <div class="field">
        <%= submit_tag "Gerar arquivo de saída", class: "ui button"%>
      </div>
    <% end %>
  </div>
</div>